[package]
name = "aoc2022_4"
version = "0.1.0"
authors = ["Ladislas 'Ladislus' WALCAK"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
